apiVersion: v1
kind: Service
metadata:
  name: docker-practice-srv
spec:
  type: NodePort
  selector:
    app: docker-practice
  ports:
    - name: docker-practice
      protocol: TCP
      port: 4000
      targetPort: 4000
